language: python
python:
- '3.3'

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pipenv

install:
  - pip install pipenv
  - pipenv install

script:
  - python to_css.py > nightowl-pygments.css
  - cat nightowl-pygments.css
